function [gray] = GetImageFromContour(contour, imgSize)
%%% This code is written by BAMI LAB %%%
% Get image from contour
%   input  :
%       contour = the image's contour
%       imgSize = the image's size
%
%   output :
%       gray = the image generated by contour

h = figure(); set(gcf, 'Visible', 'off');
rgb = logical(false(imgSize));
imshow(rgb, 'Border', 'tight'); hold on;

fill(contour(:,1), contour(:,2), 'w');

rgb = frame2im(getframe(h));
gray = rgb2gray(rgb);
gray = logical(gray);

sizeContour = size(contour);
for j=1:sizeContour(1)
    gray(contour(j,2), contour(j,1)) = 1;
end

hold off;
close(h);
close all;